### PR TITLE
Fix: SyntaxError: Expected token ')'

### PR DESCRIPTION
**Pull request by gobijan**
```
// Mac OS X app was activated.
document.addEventListener('appActivated', function(e) {
    console.log(e.data);
    var appName = e.data.localizedName;
    var bundleURL = e.data.bundleURL;
}, true);
```

### CODE REVIEW

**Comment by jeff-h** [comment]
Nasty. Thank you very much :)

Would you mind updating the Wiki as well?

**Comment by gobijan** [comment]
:) You have an idea how the wiki shall be structured?

**Comment by gobijan** [comment]
BTW: Thx for creating the nodelike fork. This is what's really needed for macgap! great work :+1:

**Comment by jeff-h** [comment]
LOL sorry, wrong repo. Don't suppose you could do a pull request over on https://github.com/maccman/macgap as that's where macgap fixes should really be made. Also the wiki is over there.

The nodelike fork is awesome :D Huge thanks to the node-app guys.

**Comment by gobijan** [comment]
lol I was confused and made the patch here although I meant to do it there ;D one more reason both should be merged into one.

**Comment by jeff-h** [comment]
I'd love to merge them into one, as this only adds about 1MB to the app size. The biggest downside is that with this merged in, we only have OS X 10.9+ compatibility. MacGap without this should work even on 10.6 or something, I believe. Thoughts?

**Comment by gobijan** [comment]
hmm... maybe the way would be to create a simple fs api for macgap because I guess that's what most people would make use of => reading and writing files.

do you think this could be done easily?

**Pull request merged**
